import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IPOScoreProvider } from "@/context/IPOScoreContext";
import { SimulationProvider } from "@/context/SimulationContext";
import { Navbar } from "@/components/layout/Navbar";
import { AIMentor } from "@/components/features/ai/AIMentor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen selection:bg-accent-glow/30`}
      >
        <IPOScoreProvider>
          <SimulationProvider>
            <Navbar />
            <main className="relative z-0">
              {children}
            </main>
            <AIMentor />
          </SimulationProvider>
        </IPOScoreProvider>
      </body>
    </html>
  );
}
