/**
 * @file attestationEngine.ts
 * @service os-kernel/services/security
 * @version V49
 * @description Silicon Enclave Verification Layer — StreetMP OS
 *
 * Simulates the cryptographic proof generated by AWS Nitro Enclaves or
 * Intel TDX, guaranteeing that the running code has not been tampered
 * with at the host-OS level.
 *
 * Tech Stack Lock: TypeScript · Next.js (App Router) · No Python
 * Aesthetic Lock: Obsidian & Emerald
 */

import crypto from "crypto";

// ================================================================
// TYPES
// ================================================================

export interface PlatformConfigRegister {
  /** Register index (0 = OS/Kernel, 1 = Config, 2 = App Binary) */
  index: 0 | 1 | 2;
  /** Human-readable measurement label */
  label: string;
  /** SHA-384 hex digest */
  measurement: string;
}

export interface AttestationProof {
  /** OS / Kernel execution state measurement */
  pcr0: string;
  /** Configuration hash measurement */
  pcr1: string;
  /** Application binary hash measurement */
  pcr2: string;
  /** ISO-8601 timestamp of proof generation */
  timestamp: string;
  /**
   * HMAC-SHA-384 of the PCR triple concatenation.
   * If this diverges it signals in-flight tampering.
   */
  signature: string;
}

export interface AttestationResult {
  verified: boolean;
  proof: AttestationProof;
  registers: PlatformConfigRegister[];
  /** UNIX ms when verification ran */
  verifiedAt: number;
  /** Monotonically incrementing tamper event counter */
  tamperEvents: number;
}

// ================================================================
// CONSTANTS — Mock PCR baselines (represent a known-good boot state)
// ================================================================

const BASELINE_PCR0 =
  "a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90";

const ENCLAVE_MASTER_KEY = "STREETMP_ENCLAVE_MASTER_SECRET_V49";

// ================================================================
// HARDWARE ATTESTOR CLASS
// ================================================================

export class HardwareAttestor {
  private readonly baselinePcr0: string;
  private tamperCount: number = 0;
  private pollingInterval: ReturnType<typeof setInterval> | null = null;

  constructor(baselinePcr0: string = BASELINE_PCR0) {
    this.baselinePcr0 = baselinePcr0;
  }

  // ── Private Helpers ─────────────────────────────────────────────

  /** Reads a mock Platform Configuration Register by generating a stable SHA-384. */
  private readPCR(index: 0 | 1 | 2): PlatformConfigRegister {
    const labels: Record<0 | 1 | 2, string> = {
      0: "OS_KERNEL_STATE",
      1: "CONFIG_LOCK_V49",
      2: "APP_BINARY_HASH",
    };

    const seeds: Record<0 | 1 | 2, string> = {
      0: this.baselinePcr0,
      1: "STREETMP_OS_V49_CONFIG_LOCK",
      2: "STREETMP_PROXY_ROUTER_STATE",
    };

    const measurement =
      index === 0
        ? this.baselinePcr0 // PCR0 is fixed — any deviation = tamper event
        : crypto.createHash("sha384").update(seeds[index]).digest("hex");

    return { index, label: labels[index], measurement };
  }

  // ── Public API ───────────────────────────────────────────────────

  /**
   * Generates a cryptographic proof that maps the physical state of the host
   * CPU enclave across all three Platform Configuration Registers.
   *
   * Equivalent to `nsm-cli describe-pcr` on AWS Nitro.
   */
  public generateSiliconProof(): AttestationProof {
    const r0 = this.readPCR(0);
    const r1 = this.readPCR(1);
    const r2 = this.readPCR(2);

    const now = Date.now();
    const payload = `${r0.measurement}:${r1.measurement}:${r2.measurement}:${now}`;
    const signature = crypto
      .createHmac("sha384", ENCLAVE_MASTER_KEY)
      .update(payload)
      .digest("hex");

    return {
      pcr0: r0.measurement,
      pcr1: r1.measurement,
      pcr2: r2.measurement,
      timestamp: new Date(now).toISOString(),
      signature,
    };
  }

  /**
   * Verifies enclave integrity by:
   *  1. Regenerating the expected HMAC from the proof's own PCRs.
   *  2. Comparing PCR0 measurement against the known-good baseline.
   *
   * If either check fails, the enclave is considered compromised.
   *
   * @param expectedHash  Optional override for the PCR0 baseline.
   */
  public verifyEnclaveIntegrity(expectedHash?: string): AttestationResult {
    const proof = this.generateSiliconProof();
    const registers: PlatformConfigRegister[] = [
      this.readPCR(0),
      this.readPCR(1),
      this.readPCR(2),
    ];

    // Re-derive expected signature (timestamp-agnostic, use proof.timestamp)
    const ts = new Date(proof.timestamp).getTime();
    const expectedPayload = `${proof.pcr0}:${proof.pcr1}:${proof.pcr2}:${ts}`;
    const expectedSig = crypto
      .createHmac("sha384", ENCLAVE_MASTER_KEY)
      .update(expectedPayload)
      .digest("hex");

    const signatureValid = proof.signature === expectedSig;

    const baseline = expectedHash ?? this.baselinePcr0;
    const pcr0Valid = proof.pcr0 === baseline;

    const verified = signatureValid && pcr0Valid;

    if (!verified) {
      this.tamperCount += 1;
      const reason = !signatureValid
        ? "HMAC signature mismatch — in-flight PCR tampering detected"
        : "PCR0 deviation — host OS state has changed";
      console.error(
        `[V49:FATAL_ENCLAVE_COMPROMISE] tamperEvent=${this.tamperCount} — ${reason}`
      );
    } else {
      console.info(
        `[V49:Attestation] ✅ Silicon Root of Trust Verified. PCR0=${proof.pcr0.slice(0, 16)}…`
      );
    }

    return {
      verified,
      proof,
      registers,
      verifiedAt: Date.now(),
      tamperEvents: this.tamperCount,
    };
  }

  /**
   * Continuously polls enclave integrity on `intervalMs` cadence.
   * Fires `onCompromise` callback if verification fails.
   *
   * @param intervalMs   Poll interval in milliseconds (default 5 000 ms).
   * @param onCompromise Callback invoked with the failed `AttestationResult`.
   */
  public startContinuousPolling(
    intervalMs = 5_000,
    onCompromise?: (result: AttestationResult) => void
  ): void {
    if (this.pollingInterval) {
      console.warn("[V49:Attestation] Polling already active — ignoring duplicate start.");
      return;
    }

    this.pollingInterval = setInterval(() => {
      const result = this.verifyEnclaveIntegrity();
      if (!result.verified && onCompromise) {
        onCompromise(result);
      }
    }, intervalMs);

    console.info(`[V49:Attestation] Continuous enclave polling started (every ${intervalMs}ms).`);
  }

  /** Stops the continuous polling loop. */
  public stopPolling(): void {
    if (this.pollingInterval) {
      clearInterval(this.pollingInterval);
      this.pollingInterval = null;
      console.info("[V49:Attestation] Continuous enclave polling stopped.");
    }
  }

  /** Returns the current tamper-event count. */
  public getTamperCount(): number {
    return this.tamperCount;
  }
}

// ================================================================
// SINGLETON EXPORT — consumed by the proxy pipeline
// ================================================================
export const globalSecurityAttestor = new HardwareAttestor();
